POST http://localhost:5237/api/auth/register
Content-Type: application/json

{
  "nombreCompleto": "Usuario Prueba",
  "correo": "prueba@gmail.com",
  "contrasena": "Prueba123!",
  "telefono": "99999999",
  "fechaNacimiento": "2000-01-01"
}